### PR TITLE
Fix no table is replicated when excludeTableRegex is set while includeTableRegex is nil

### PR DESCRIPTION
**Pull request by gaojijun**
fix https://github.com/go-mysql-org/go-mysql/issues/873

### CODE REVIEW

**Comment by lance6716** [comment]
Thanks, please fix the lint error

```
  canal/canal.go:299: File is not `goimports`-ed (goimports)
```

And can you update the `canal_test.go` like `TestCanalFilter` to add an unit test for it?

**Comment by gaojijun** [comment]
> Thanks, please fix the lint error
> 
> ```
>   canal/canal.go:299: File is not `goimports`-ed (goimports)
> ```
> 
> And can you update the `canal_test.go` like `TestCanalFilter` to add an unit test for it?

Done

**Comment by lance6716** [comment]
Hi, I mean add a test to explain your change. I manually deleted line 302~303 and the test `TestIncludeExcludeTableRegex` can still pass. I want a failed test without the change as issue said

**Comment by lance6716** [comment]
Can you also update the comment of `IncludeTableRegex` and `ExcludeTableRegex` to explain the behaviout when either is not set? 

My last concern is by Hyrum's Law we should not change the behaviour of API, but I think this change does no harm. Because the old behaviour will replicate nothing so there should be no user using it. As a user, I directly use `BinlogSyncer` and don't use canal package, @froot can you give your opinion?

rest lgtm

**Comment by gaojijun** [comment]
// Default IncludeTableRegex and ExcludeTableRegex are empty, this will include all tables

@lance6716 Is this comment good enough? It's already in the code.

**Comment by lance6716** [comment]
> // Default IncludeTableRegex and ExcludeTableRegex are empty, this will include all tables
> 
> @lance6716 Is this comment good enough? It's already in the code.

It means both are empty, not one of them is empty

**Comment by gaojijun** [comment]
> > // Default IncludeTableRegex and ExcludeTableRegex are empty, this will include all tables
> > @lance6716 Is this comment good enough? It's already in the code.
> 
> It means both are empty, not one of them is empty

updated

**Review by lance6716 — APPROVED** [review]

**Pull request merged**
