### PR TITLE
fix: UnsignedColumns idx out range

### PR DESCRIPTION
**Pull request by guihouchang**
fix:#713

### CODE REVIEW

**Comment by atercattus** [comment]
Hello.
Can you add a test case ([based on this](https://github.com/go-mysql-org/go-mysql/issues/713#issuecomment-1182044043)) that will panic?

**Comment by atercattus** [comment]
Same fix is [here](https://github.com/go-mysql-org/go-mysql/pull/689)

**Comment by guihouchang** [comment]
> Hello. Can you add a test case ([based on this](https://github.com/go-mysql-org/go-mysql/issues/713#issuecomment-1182044043)) that will panic?

I don't know how to add this unit test.It looks very complicated. I need help

**Comment by lance6716** [comment]
> > Hello. Can you add a test case ([based on this](https://github.com/go-mysql-org/go-mysql/issues/713#issuecomment-1182044043)) that will panic?
> 
> I don't know how to add this unit test. It looks very complicated. I need help

Hi, do you find problems when try to use the test framework, or have no idea how to test it?

**Comment by lance6716** [comment]
> have no idea how to test it, plz show me a example

In fact I don't use canal, do you have a real use case that will meet this problem? We can mimic that API invocation and binlog content.

**Comment by lance6716** [comment]
replaced by https://github.com/go-mysql-org/go-mysql/pull/856

**Pull request closed without merging**
