### PR TITLE
Support LOCAL INFILE request

### PR DESCRIPTION
**Pull request by masahide**
Make `LOAD DATA LOCAL INFILE` available.

### CODE REVIEW

**Review by lance6716 — COMMENTED** [review]
Even if we turn on the capability flag, in fact we don't support LOAD DATA INFILE?

https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_com_query_response_local_infile_request.html

It wil return a 0xFB packet and searching for `LocalInFile_HEADER` you can see we simply return `ErrMalformPacket`

**Comment by masahide** [comment]
I apologize for the confusion, you're absolutely right. I used go-mysql/client to create a MySQL proxy. 
When using the LOCAL INFILE in this proxy, it is necessary to configure the CLIENT_LOCAL_FILES capability when connecting from go-mysql/client to the MySQL server, and this modification was required for that. This proxy operates by using go-mysql/client only for MySQL handshake, and after connection, the client's net.Conn is directly transferred to the server-side net.Conn, hence making the LOCAL INFILE operational with just the LocalInFile_HEADER.
https://github.com/masahide/mysql8-audit-proxy/blob/main/pkg/mysqlproxy/clntsess.go#L33-L38

Project top page: https://github.com/masahide/mysql8-audit-proxy

**Review by lance6716 — APPROVED** [review]
lgtm. Can you help fix the linter? If you don't have enough time, I'll make a commit tomorrow

**Comment by lance6716** [comment]
btw, what's your golang version? in https://github.com/go-mysql-org/go-mysql/issues/799 we are considering to drop support for older golang versions

**Comment by masahide** [comment]
I am using go version 1.20.

**Pull request merged**
