### PR TITLE
This repo is abandoned

### PR DESCRIPTION
**Pull request by atercattus**

### CODE REVIEW

**Comment by lance6716** [comment]
Hi, I noticed there's "Call for Committer/Maintainer" in readme. Did you try that?

**Comment by atercattus** [comment]
@lance6716, we talked with siddontang last year, and I got committer rights. But it is not enough to change the required Travis-CI step. And siddontang does not answer me now.
I have been waiting for this since last year and now I have made the decision to continue development in my repo.

**Comment by siddontang** [comment]
sorry @atercattus 

I am too busy these days... 

Maybe it is better to create a go-mysql org and then we can maintain it together?

**Comment by atercattus** [comment]
Hurray, you are here.

I will be glad to any solution to develop the project further (and not to lose the PRs that are in my repo :)

`go-mysql` already taken. May be `go-mysql-org`? Or we could choose another way.

**Comment by atercattus** [comment]
Ok, I moved my repo to https://github.com/go-mysql-org/go-mysql and added you

**Comment by siddontang** [comment]
maybe it is better for me to do the migration?

**Comment by atercattus** [comment]
> maybe it is better for me to do the migration?

Yes, it helps save all issues and PRs.

I moved my repo back. Org is empty now. I will wait for you.

**Comment by siddontang** [comment]
thanks @atercattus 

done :-)

**Comment by atercattus** [comment]
Thank you too :)

I'll transfer the new PRs later today.

**Pull request closed without merging**
