### PR TITLE
fix: return null values properly in proxy mode

### PR DESCRIPTION
**Pull request by btoonk**
When using go-mysql in proxy mode, the null values are not handled correctly.
This PR is an attempt to solve this. 

The same logic is already in use in the BuildSimpleTextResultset function.

### CODE REVIEW

**Comment by skoef** [comment]
Thanks for your contribution! Could you extend any existing test case to prove your fix solves the issue?

**Comment by lance6716** [comment]
Hi @btoonk , I found a bit different place to fix this issue.

`LengthEncodedInt` and `PutLengthEncodedInt` in util.go seems are inverse functions of each other, can you check if we add the `n=0` case in `LengthEncodedInt` the issue will also be fixed?

If it's OK, can you add an unit test to verify that the two functions can handle the output of each other and return the original input?

**Comment by btoonk** [comment]
@skoef I added a test that proves this fix solved the issue.

**Comment by btoonk** [comment]
@lance6716 I don't think we can do it in PutLengthEncodedInt (or in PutLengthEncodedString), I think not all data that is nil (or n=0) is equal to NULL (0xfb), I think that is only the case for row values. That is why we can do it in the writeFieldValues function.

**Comment by lance6716** [comment]
Hi, I'll try to fix the CI problem and then come to your PR 😄

**Review by lance6716 — APPROVED** [review]

**Pull request merged**
