### PR TITLE
Remove failover

### PR DESCRIPTION
**Pull request by dveeden**
The `failover` part of go-mysql does failover in case of the failure of a primary in a MySQL topology and it also refactors the topology by changing replication on hosts to make sure they follow the new primary.

However there are various issues with this:

1. This is not production ready according to `failover/doc.go`
2. This uses the `master`/`slave` terms instead of `source/primary`/`replica`.
3. This uses statements that have changed in recent MySQL versions (`SHOW MASTER...`, `CHANGE MASTER...`, `SHOW SLAVE...`)
4. MariaDB support looks incomplete. There is a `MariadbGTIDHandler` but `Failover()` returns an error if the flavor is set to MariaDB.
5. There are better solutions for HA like Orchestrator, MySQL Group Replication (part of InnoDB Cluster), Galera and TiDB.
6. The code has a lack of timeouts.
7. This doesn't support multiple levels of replicas.

I think we should remove this unless there is a good use case for this that warrants keeping this and refactoring this completely.

### Related

- #866

### CODE REVIEW

**Review by lance6716 — APPROVED** [review]

**Comment by lance6716** [comment]
(Wait for another review)

**Comment by dveeden** [comment]
PTAL @atercattus

**Comment by lance6716** [comment]
I'll merge this PR after CI passed. As for release, I want to wait until all active PRs are merged

**Comment by svaroqui** [comment]
Note that Signal18 maintains a golang open source solution replication-manager for multiple topology on MariaDB and MySQL, battle tested on many use cases https://github.com/signal18/replication-manager/

**Comment by dveeden** [comment]
> Note that Signal18 maintains a golang open source solution replication-manager for multiple topology on MariaDB and MySQL, battle tested on many use cases https://github.com/signal18/replication-manager/

You may want to send a PR to https://github.com/shlomi-noach/awesome-mysql?tab=readme-ov-file#ha to get this listed there. And maybe consider doing a talk about this at FOSDEM as well.

**Comment by atercattus** [comment]
Thanks, @lance6716. I believe you are doing a great job while I am overwhelmed with work :)

If we remove functionality from this project, it is worth adding a link to alternative methods to our documentation.

**Comment by svaroqui** [comment]
> > Note that Signal18 maintains a golang open source solution replication-manager for multiple topology on MariaDB and MySQL, battle tested on many use cases https://github.com/signal18/replication-manager/
> 
> You may want to send a PR to https://github.com/shlomi-noach/awesome-mysql?tab=readme-ov-file#ha to get this listed there. And maybe consider doing a talk about this at FOSDEM as well.

Thanks, i'll check if MySQL&Friends  is back in FOSDEM this year if not should check with MariaDB for a session in their room hope to see you there and thanks again for go-mysql that we use in many cases in replication-manager like for tracking binlog for PITR

**Pull request merged**
