### PR TITLE
trim space of GTID

### PR DESCRIPTION
**Pull request by zr-hebo**

### CODE REVIEW

**Comment by lance6716** [comment]
Could you explain or give some steps to reproduce why there's space in `UUIDSet.String()`

**Comment by zr-hebo** [comment]
> Could you explain or give some steps to reproduce why there's space in `UUIDSet.String()`

I make some test, String() contain space do not recurrent. maybe I got it wrong or If it occur I will catch it.

**Comment by zr-hebo** [comment]
I make some test, String() contain space do not recurrent. maybe I got it wrong or If it occur I will catch it.

**Comment by lance6716** [comment]
> I make some test, String() contain space do not recurrent. maybe I got it wrong or If it occur I will catch it.

no need to hurriedly close this PR, could you provide steps of your test and let us take a look?

**Comment by zr-hebo** [comment]
> > I make some test, String() contain space do not recurrent. maybe I got it wrong or If it occur I will catch it.
> 
> no need to hurriedly close this PR, could you provide steps of your test and let us take a look?

I saw a GTID contain space many month ago, I simply trim space and not pay too much attention
. If I see it again, I will make more test and reopen this PR.

**Pull request closed without merging**
