### PR TITLE
Add a optional function to decode optional meta of table map event

### PR DESCRIPTION
**Pull request by zing22845**
I have a hacked version of MySQL which has a UDF optional meta in table map event. I managed to add a TableMapOptionalMetaDecodeFunc to decode the optional meta.

### CODE REVIEW

**Comment by zing22845** [comment]
PTAL @lance6716

**Review by lance6716 — COMMENTED** [review]
lgtm with a quick glance, will check again tomorrow.

Would you mind to share with us what's the provider of the hacked MySQL? Is it a cloud RDS?

**Comment by zing22845** [comment]
It's ok.

**Comment by zing22845** [comment]
We added the column info for rows events in earlier 5.6 version. Unfortunately these instances can not be upgrade and our DTS depends on those infos in optional meta.

**Review by lance6716 — APPROVED** [review]

**Pull request merged**
