### PR TITLE
fix: fix slice init length

### PR DESCRIPTION
**Pull request by cuishuang**
The intention here should be to initialize a slice with a capacity of 4 rather than initializing the length of this slice.

### CODE REVIEW

**Comment by dveeden** [comment]
Can you explain the issue you're trying to fix? Is this for functionality and/or performance?

**Comment by lance6716** [comment]
Hi, please fix ci

**Comment by dveeden** [comment]
@cuishuang could you fix the failing checks?

**Comment by cuishuang** [comment]
> @cuishuang could you fix the failing checks?

Sorry, it seems that my changes were incorrect. I found that my detection tool has a high false positive rate when the slice type is byte.

Sorry for wasting your time.

**Pull request closed without merging**
