### PR TITLE
update dependency

### PR DESCRIPTION
**Pull request by Ehco1996**
```
$ go mod why github.com/myesui/uuid
# github.com/myesui/uuid
github.com/go-mysql-org/go-mysql/canal
github.com/pingcap/parser
github.com/pingcap/parser.test
github.com/pingcap/tidb/types
github.com/pingcap/tidb/types.test
github.com/pingcap/tidb/domain
github.com/pingcap/tidb/ddl
github.com/twinj/uuid
github.com/twinj/uuid.test
github.com/myesui/uuid
```

but github.com/myesui/uuid is deleted. so this PR updates github.com/pingcap/parser

### CODE REVIEW

**Review by lance6716 — APPROVED** [review]

**Comment by ChampionL** [comment]
when will the new version be released?

**Comment by ChampionL** [comment]
@lance6716

**Comment by lance6716** [comment]
> when will the new version be released?

I have no suggestions. WDYT @atercattus

**Comment by atercattus** [comment]
I'll do it today. OK?

**Comment by atercattus** [comment]
Sorry for the long waiting, but I did it finally.

**Pull request merged**
